In [1]:
import pandas as pd 
df = pd.read_csv('end-to-end/report_complete_processed.csv')

In [2]:
df.columns

Index(['trace_name', 'number_of_requests', 'wsr', 'slab_size', 'slab_cnt',
       'rebalanceDiffRatio', 'rebalance_strategy', 'allocator', 'tag',
       'throughput', 'rebalanced_slabs', 'miss_ratio', 'n_rebalanced_slabs',
       'monitor_interval', 'n_alloc_failures', 'uuid',
       'miss_ratio_reduction_from_disabled',
       'miss_ratio_reduction_from_lru_disabled', 'tuned_improvement'],
      dtype='object')

In [4]:
df[(df['allocator'] == 'LRU') & (df['rebalance_strategy'] == 'eviction-rate')].sort_values(by=['miss_ratio_reduction_from_disabled'])

,trace_name,number_of_requests,wsr,slab_size,slab_cnt,rebalanceDiffRatio,rebalance_strategy,allocator,tag,throughput,rebalanced_slabs,miss_ratio,n_rebalanced_slabs,monitor_interval,n_alloc_failures,uuid,miss_ratio_reduction_from_disabled,miss_ratio_reduction_from_lru_disabled,tuned_improvement
1664,twitter_cluster49,799295267,0.010,1,54,0.1,eviction-rate,LRU,NaN,608167.490278,270,0.465548,270,50000,0,twitter_cluster49-070c9b8bc99b7c3047c3b1a18b76...,-0.078684,-0.078684,NaN
799,twitter_cluster19,2006896318,0.100,1,2993,0.1,eviction-rate,LRU,NaN,499059.254558,3982,0.315759,3982,50000,0,twitter_cluster19-28519e5c482e269bd2f1110a1708...,-0.072342,-0.072342,NaN
1040,twitter_cluster29,6920247859,0.010,1,790,0.1,eviction-rate,LRU,NaN,849459.226084,1682,0.173706,1682,50000,4,twitter_cluster29-324793a2301788899ba768218e86...,-0.072039,-0.072039,NaN
1060,twitter_cluster29,6920247859,0.100,1,7891,0.1,eviction-rate,LRU,NaN,491130.964008,20062,0.109000,20062,50000,1,twitter_cluster29-5802f89c90b357a421f6f796ea92...,-0.061504,-0.061504,NaN
1565,twitter_cluster45,227773739,0.100,1,597,0.1,eviction-rate,LRU,NaN,654204.724386,383,0.431755,383,50000,6,twitter_cluster45-e5064094f862616a10a8fdb2892e...,-0.049559,-0.049559,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1834,twitter_cluster53,246508262,0.010,1,107,0.1,eviction-rate,LRU,NaN,312389.525769,227,0.237636,227,50000,4,twitter_cluster53-39cfec386d7d4087505c6db25431...,0.073829,0.073829,NaN
1811,twitter_cluster53,246508262,0.004,1,43,0.1,eviction-rate,LRU,NaN,246845.930967,32,0.299039,32,50000,4,twitter_cluster53-18891d4fb6f391e60d212e09e2cb...,0.078205,0.078205,NaN
610,twitter_cluster11,2731402190,0.100,1,538,0.1,eviction-rate,LRU,NaN,787197.342747,23176,0.161915,23176,50000,2,twitter_cluster11-9f222924c969e8f9dd0d8cde5e94...,0.102011,0.102011,NaN
1744,twitter_cluster50,139655585,0.100,1,4149,0.1,eviction-rate,LRU,NaN,396185.787661,2363,0.139839,2363,50000,0,twitter_cluster50-66c0a4c73d58a12f3e638bf30477...,0.151280,0.151280,NaN
1725,twitter_cluster50,139655585,0.010,1,415,0.1,eviction-rate,LRU,NaN,351965.088210,1917,0.327253,1917,50000,24,twitter_cluster50-f48a3ff28fe6e54d0db841c5f5e6...,0.288846,0.288846,NaN

In [5]:
def filter_df(df, filters):
    filtered_df = df.copy()
    
    for column, value in filters.items():
        if column in df.columns:
            filtered_df = filtered_df[filtered_df[column] == value]
        else:
            print(f"Warning: Column '{column}' not found in DataFrame")
    
    return filtered_df

In [10]:
filtered_data = filter_df(df, {'allocator': 'LRU', 'trace_name': 'twitter_cluster49', 'wsr': 0.01})
filtered_data.sort_values(by=['miss_ratio'])[['rebalance_strategy', 'miss_ratio', 'rebalanced_slabs', 'uuid']]

,rebalance_strategy,miss_ratio,rebalanced_slabs,uuid
1661,marginal-hits-tuned,0.386244,26,twitter_cluster49-e3f4e8f22baa1b771438bf45d20b...
1663,tail-age,0.386864,0,twitter_cluster49-c9e7746a5d167f058e128fd22d9b...
1666,disabled,0.386864,0,twitter_cluster49-f0daf5073961527b3afadd89e6b5...
1662,marginal-hits,0.417838,15984,twitter_cluster49-eb0e53db2f7bac74113a85c8073a...
1664,eviction-rate,0.465548,270,twitter_cluster49-070c9b8bc99b7c3047c3b1a18b76...
1665,hits,0.497902,37,twitter_cluster49-cc0fac143d4a90ba4944ab7aec35...

In [12]:
filtered_data = filter_df(df, {'allocator': 'LRU', 'trace_name': 'twitter_cluster19', 'wsr': 0.01})
filtered_data.sort_values(by=['miss_ratio'])[['rebalance_strategy', 'miss_ratio', 'rebalanced_slabs', 'uuid']]

,rebalance_strategy,miss_ratio,rebalanced_slabs,uuid
781,marginal-hits-tuned,0.508401,782,twitter_cluster19-88b7e59c2e7e3cd50b0d6792588c...
782,marginal-hits,0.508894,40066,twitter_cluster19-4cd771af01e20a9bf8c6a2bdfc31...
783,hits,0.511749,550,twitter_cluster19-eabda61fbc0600d81d417541271f...
780,tail-age,0.515876,574,twitter_cluster19-2fdb1903887f8e15a7306479bd6c...
779,eviction-rate,0.526081,235,twitter_cluster19-7d3a420f392175b0aefae0a0cbf6...
778,disabled,0.575939,0,twitter_cluster19-05d7d95835ed39fde1a58862cab5...